# How many codes to check concurrently?
# Windows supports maximum of 512.
# On *nix operating systems, this restriction is much looser.
# The limit on *nix can be seen with the command `ulimit -Hn`.
# Try different values and see which ones give you the best performance.
max_connections = 512

# Leave blank if you want the nitro codes to be only saved to the file_name.
webhook_url = "https://discord.com/api/webhooks/1220326454857044062/FqofKkbX8AFL8_TS3yLY_SzRwYRz-UVlBu3AQk-llohUk_e2-75eSNu65oJ5NGQDJAf1"

# The number of seconds to wait for a request to the Discord API.
timeout = 10

# Path to the file where valid codes are to be saved.
file_name = "./nitro_codes.txt"
